FROM node:22-bookworm-slim AS base

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg curl && apt-get clean

FROM base AS dev
WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

RUN adduser --system --uid 1001 --ingroup node nextjs
RUN mkdir -p /app/.next/cache/images && chown -R nextjs:node /app/.next/cache

COPY package.json ./

RUN npm install --package-lock-only --no-audit

COPY . .

RUN npm install

USER nextjs

CMD ["npm", "run", "dev"]